CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    telegram_id bigint NOT NULL,
    username character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE surveys (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    title character varying(500) NOT NULL,
    description text,
    creator_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    allow_multiple_responses boolean NOT NULL DEFAULT FALSE,
    show_results boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_surveys" PRIMARY KEY (id),
    CONSTRAINT fk_surveys_creator FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE questions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    survey_id integer NOT NULL,
    question_text text NOT NULL,
    question_type integer NOT NULL,
    order_index integer NOT NULL,
    is_required boolean NOT NULL DEFAULT TRUE,
    options_json jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_questions" PRIMARY KEY (id),
    CONSTRAINT chk_order_index CHECK (order_index >= 0),
    CONSTRAINT chk_question_type CHECK (question_type IN (0, 1, 2, 3)),
    CONSTRAINT fk_questions_survey FOREIGN KEY (survey_id) REFERENCES surveys (id) ON DELETE CASCADE
);

CREATE TABLE responses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    survey_id integer NOT NULL,
    respondent_telegram_id bigint NOT NULL,
    is_complete boolean NOT NULL DEFAULT FALSE,
    started_at timestamp with time zone,
    submitted_at timestamp with time zone,
    CONSTRAINT "PK_responses" PRIMARY KEY (id),
    CONSTRAINT fk_responses_survey FOREIGN KEY (survey_id) REFERENCES surveys (id) ON DELETE CASCADE
);

CREATE TABLE answers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    response_id integer NOT NULL,
    question_id integer NOT NULL,
    answer_text text,
    answer_json jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_answers" PRIMARY KEY (id),
    CONSTRAINT chk_answer_not_null CHECK (answer_text IS NOT NULL OR answer_json IS NOT NULL),
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE,
    CONSTRAINT fk_answers_response FOREIGN KEY (response_id) REFERENCES responses (id) ON DELETE CASCADE
);

CREATE INDEX idx_answers_answer_json ON answers USING gin (answer_json);

CREATE INDEX idx_answers_question_id ON answers (question_id);

CREATE INDEX idx_answers_response_id ON answers (response_id);

CREATE UNIQUE INDEX idx_answers_response_question_unique ON answers (response_id, question_id);

CREATE INDEX idx_questions_options_json ON questions USING gin (options_json);

CREATE INDEX idx_questions_survey_id ON questions (survey_id);

CREATE UNIQUE INDEX idx_questions_survey_order_unique ON questions (survey_id, order_index);

CREATE INDEX idx_questions_type ON questions (question_type);

CREATE INDEX idx_responses_complete ON responses (is_complete) WHERE is_complete = true;

CREATE INDEX idx_responses_submitted_at ON responses (submitted_at) WHERE submitted_at IS NOT NULL;

CREATE INDEX idx_responses_survey_id ON responses (survey_id);

CREATE INDEX idx_responses_survey_respondent ON responses (survey_id, respondent_telegram_id);

CREATE INDEX idx_surveys_created_at ON surveys (created_at DESC);

CREATE INDEX idx_surveys_creator_active ON surveys (creator_id, is_active);

CREATE INDEX idx_surveys_creator_id ON surveys (creator_id);

CREATE INDEX idx_surveys_is_active ON surveys (is_active) WHERE is_active = true;

CREATE UNIQUE INDEX idx_users_telegram_id ON users (telegram_id);

CREATE INDEX idx_users_username ON users (username) WHERE username IS NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251105190107_InitialCreate', '9.0.10');

ALTER TABLE users ADD last_login_at timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251106000001_AddLastLoginAtToUser', '9.0.10');

ALTER TABLE surveys ADD code character varying(10);

CREATE UNIQUE INDEX idx_surveys_code ON surveys (code) WHERE code IS NOT NULL;


                UPDATE surveys
                SET code = UPPER(SUBSTRING(MD5(RANDOM()::text || id::text), 1, 6))
                WHERE code IS NULL;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251109000001_AddSurveyCodeColumn', '9.0.10');

ALTER TABLE questions ADD media_content jsonb;

CREATE INDEX idx_questions_media_content ON questions USING gin (media_content);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251118191617_AddMediaContentToQuestion', '9.0.10');

COMMIT;

