// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurveyBot.Infrastructure.Data;

#nullable disable

namespace SurveyBot.Infrastructure.Migrations
{
    [DbContext(typeof(SurveyBotDbContext))]
    [Migration("20251123131359_CleanSlateNextQuestionDeterminant")]
    partial class CleanSlateNextQuestionDeterminant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SurveyBot.Core.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_json");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("NextQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("next_question_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("ResponseId")
                        .HasColumnType("integer")
                        .HasColumnName("response_id");

                    b.HasKey("Id");

                    b.HasIndex("AnswerJson")
                        .HasDatabaseName("idx_answers_answer_json");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AnswerJson"), "gin");

                    b.HasIndex("NextQuestionId")
                        .HasDatabaseName("idx_answers_next_question_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("idx_answers_question_id");

                    b.HasIndex("ResponseId")
                        .HasDatabaseName("idx_answers_response_id");

                    b.HasIndex("ResponseId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("idx_answers_response_question_unique");

                    b.ToTable("answers", null, t =>
                        {
                            t.HasCheckConstraint("chk_answer_not_null", "answer_text IS NOT NULL OR answer_json IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<string>("MediaContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("media_content");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("QuestionType")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer")
                        .HasColumnName("survey_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaContent")
                        .HasDatabaseName("idx_questions_media_content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MediaContent"), "gin");

                    b.HasIndex("OptionsJson")
                        .HasDatabaseName("idx_questions_options_json");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OptionsJson"), "gin");

                    b.HasIndex("QuestionType")
                        .HasDatabaseName("idx_questions_type");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("idx_questions_survey_id");

                    b.HasIndex("SurveyId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("idx_questions_survey_order_unique");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("chk_order_index", "order_index >= 0");

                            t.HasCheckConstraint("chk_question_type", "question_type IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("idx_question_options_question_id");

                    b.HasIndex("QuestionId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("idx_question_options_question_order_unique");

                    b.ToTable("question_options", null, t =>
                        {
                            t.HasCheckConstraint("chk_question_option_order_index", "order_index >= 0");
                        });
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_complete");

                    b.Property<long>("RespondentTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("respondent_telegram_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer")
                        .HasColumnName("survey_id");

                    b.Property<string>("VisitedQuestionIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("visited_question_ids")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IsComplete")
                        .HasDatabaseName("idx_responses_complete")
                        .HasFilter("is_complete = true");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("idx_responses_submitted_at")
                        .HasFilter("submitted_at IS NOT NULL");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("idx_responses_survey_id");

                    b.HasIndex("VisitedQuestionIds")
                        .HasDatabaseName("idx_responses_visited_question_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("VisitedQuestionIds"), "gin");

                    b.HasIndex("SurveyId", "RespondentTelegramId")
                        .HasDatabaseName("idx_responses_survey_respondent");

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultipleResponses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_multiple_responses");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("ShowResults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_results");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_surveys_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_surveys_created_at");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("idx_surveys_creator_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_surveys_is_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("CreatorId", "IsActive")
                        .HasDatabaseName("idx_surveys_creator_active");

                    b.ToTable("surveys", (string)null);
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("idx_users_telegram_id");

                    b.HasIndex("Username")
                        .HasDatabaseName("idx_users_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Answer", b =>
                {
                    b.HasOne("SurveyBot.Core.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_question");

                    b.HasOne("SurveyBot.Core.Entities.Response", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_response");

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Question", b =>
                {
                    b.HasOne("SurveyBot.Core.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_survey");

                    b.OwnsOne("SurveyBot.Core.ValueObjects.NextQuestionDeterminant", "DefaultNext", b1 =>
                        {
                            b1.Property<int>("QuestionId")
                                .HasColumnType("integer");

                            b1.Property<int?>("NextQuestionId")
                                .HasColumnType("integer")
                                .HasColumnName("default_next_question_id")
                                .HasAnnotation("Relational:JsonPropertyName", "nextQuestionId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("default_next_step_type")
                                .HasAnnotation("Relational:JsonPropertyName", "type");

                            b1.HasKey("QuestionId");

                            b1.ToTable("questions");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("DefaultNext");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.QuestionOption", b =>
                {
                    b.HasOne("SurveyBot.Core.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_question");

                    b.OwnsOne("SurveyBot.Core.ValueObjects.NextQuestionDeterminant", "Next", b1 =>
                        {
                            b1.Property<int>("QuestionOptionId")
                                .HasColumnType("integer");

                            b1.Property<int?>("NextQuestionId")
                                .HasColumnType("integer")
                                .HasColumnName("next_question_id")
                                .HasAnnotation("Relational:JsonPropertyName", "nextQuestionId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("next_step_type")
                                .HasAnnotation("Relational:JsonPropertyName", "type");

                            b1.HasKey("QuestionOptionId");

                            b1.ToTable("question_options");

                            b1.WithOwner()
                                .HasForeignKey("QuestionOptionId");
                        });

                    b.Navigation("Next");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Response", b =>
                {
                    b.HasOne("SurveyBot.Core.Entities.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_responses_survey");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Survey", b =>
                {
                    b.HasOne("SurveyBot.Core.Entities.User", "Creator")
                        .WithMany("Surveys")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveys_creator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Response", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("SurveyBot.Core.Entities.User", b =>
                {
                    b.Navigation("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
