#!/bin/sh
# =============================================================================
# Update Frontend Ngrok URLs Script
# =============================================================================
# This script fetches current ngrok URLs and updates the frontend .env file
# Run this script whenever ngrok restarts to keep frontend in sync
#
# Usage:
#   bash scripts/update-frontend-ngrok-urls.sh
#   # Then rebuild frontend: docker-compose up -d --build frontend
# =============================================================================

set -e

NGROK_API_URL="${NGROK_API_URL:-http://localhost:4040}"
ENV_FILE="frontend/.env.ngrok"

echo "============================================"
echo "Updating Frontend Ngrok URLs"
echo "============================================"
echo ""

# Function to get API tunnel URL
get_api_url() {
    curl -s "$NGROK_API_URL/api/tunnels/api" | \
        grep -o '"public_url":"https://[^"]*' | \
        head -1 | \
        sed 's/"public_url":"//'
}

# Function to get Frontend tunnel URL
get_frontend_url() {
    curl -s "$NGROK_API_URL/api/tunnels/frontend" | \
        grep -o '"public_url":"https://[^"]*' | \
        head -1 | \
        sed 's/"public_url":"//'
}

# Get API tunnel URL
echo "Fetching API tunnel URL..."
API_URL=$(get_api_url 2>/dev/null || echo "")

if [ -z "$API_URL" ] || [ "$API_URL" = "null" ]; then
    echo "ERROR: Could not fetch API ngrok URL"
    echo "Make sure ngrok is running and API tunnel is active"
    echo "Check: http://localhost:4040"
    exit 1
fi

echo "✓ API URL: $API_URL"

# Get Frontend tunnel URL
echo "Fetching Frontend tunnel URL..."
FRONTEND_URL=$(get_frontend_url 2>/dev/null || echo "")

if [ -z "$FRONTEND_URL" ] || [ "$FRONTEND_URL" = "null" ]; then
    echo "WARNING: Could not fetch Frontend ngrok URL"
    echo "Frontend tunnel may not be configured or running"
    FRONTEND_URL=""
fi

if [ -n "$FRONTEND_URL" ]; then
    echo "✓ Frontend URL: $FRONTEND_URL"
fi

# Create or update .env.ngrok file
echo ""
echo "Writing to $ENV_FILE..."

cat > "$ENV_FILE" <<EOF
# Auto-generated by update-frontend-ngrok-urls.sh
# Last updated: $(date)
#
# These environment variables override the hardcoded values in ngrok.config.ts
# They are used at build time by Vite

VITE_API_BASE_URL=${API_URL}/api
VITE_BACKEND_NGROK_URL=${API_URL}
VITE_FRONTEND_NGROK_URL=${FRONTEND_URL}
EOF

echo ""
echo "============================================"
echo "✓ Frontend .env file updated successfully"
echo "============================================"
echo ""
echo "Environment Variables:"
echo "  VITE_API_BASE_URL:        ${API_URL}/api"
echo "  VITE_BACKEND_NGROK_URL:   ${API_URL}"
echo "  VITE_FRONTEND_NGROK_URL:  ${FRONTEND_URL}"
echo ""
echo "Next Steps:"
echo "  1. Rebuild frontend container:"
echo "     docker-compose up -d --build frontend"
echo ""
echo "  2. Access frontend at:"
echo "     ${FRONTEND_URL}"
echo ""
echo "============================================"
